#Spring boot application.yml
spring:
  profiles:
    active: dev
---
spring:
  profiles : dev
  datasource:
    name: mydb
    type: com.alibaba.druid.pool.DruidDataSource
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    minIdle: 5
    maxActive: 20
    initialSize: 5
    timeBetweenEvictionRunsMillis: 3000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 'ZTM' FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    maxWait: 60000
    # open PSCache
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    filters: stat,wall,log4j2


mybatis:
  type-aliases-package: com.sunyu.k8s
  mapper-locations: classpath*:com/sunyu/k8s/mapping/*.xml
  configuration:
     log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
     map-underscore-to-camel-case: true
     cache-enabled: true
server:
  port: 8080
  tomcat:
    accesslog:
      enabled: true
      directory: ../logs
  error:
    whitelabel:
      enabled: false