#Spring boot application.yml
spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  application:
    name: dubbo-provider-demo
server:
  port: 9090
dubbo:
  registry:
    protocol: zookeeper
    address:  192.168.237.1:2181
    id: my-registry
  protocol:
    port: 80
    name: dubbo
    id: dubbo
    status: server
    host: dubbo.provider.com
  application:
    name: dubbo-provider-demo
    id: dubbo-provider-demo
    qos-enable: false
    qos-port: 2222
  scan:
    basePackages: com.test.dubbo.service
api:
  version: 1.0.0