#Spring boot application.yml
spring:
  profiles:
    active: dev
---
spring:
  profiles : dev
  kafka:
    bootstrap-servers: 172.31.205.22:9092
    consumer:
      group-id: mygroup
      auto-offset-reset: earliest
      enable-auto-commit: true
      auto-commit-interval: 100
      max-poll-records: 100
    producer:
      retries: 1
      batch-size: 16384
      buffer-memory: 33554432

server:
  port: 8080
  tomcat:
    accesslog:
      enabled: true
      directory: ../logs
  error:
    whitelabel:
      enabled: false