#Spring boot application.yml
spring:
  profiles:
    active: dev
---
spring:
  profiles : dev
server:
  port: 8080
  tomcat:
    accesslog:
      enabled: true
      directory: ../logs
  error:
    whitelabel:
      enabled: false
wss:
  server:
    host: localhost
    port: 9092