#Spring boot application.yml
spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  application:
    name: dubbo-provider-demo2
server:
  port: 9090
dubbo:
  registry:
    protocol: zookeeper
    address:  192.168.237.1:2181
    id: my-registry
  protocol:
    port: 30012
    name: dubbo
    id: dubbo
    status: server
  application:
    name: dubbo-provider-demo
    id: dubbo-provider-demo
  scan:
    basePackages: com.test.dubbo.service
api:
  version: 1.0.0