#Spring boot application.yml
spring:
  profiles:
    active: dev
---
spring:
  profiles : dev
  datasource:
    name: mydb
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/speacker?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    minIdle: 5
    maxActive: 20
    initialSize: 5
    timeBetweenEvictionRunsMillis: 3000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 'ZTM' FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    maxWait: 60000
    # open PSCache
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    filters: stat,wall,log4j2

mybatis:
  type-aliases-package: com.sunyu.prometheus
  mapper-locations: classpath*:com/sunyu/prometheus/mapping/*.xml
  configuration:
     log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
     map-underscore-to-camel-case: true
     cache-enabled: true
server:
  port: 9000
  tomcat:
    accesslog:
      enabled: true
      directory: ../logs
  error:
    whitelabel:
      enabled: false
# Metrics related configurations
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true
